#!/usr/bin/bash

#!/bin/bash

previous_step=$(cat ./previous_step.log)
s=$previous_step

if [ $s -eq 0 ]
then
    echo "Checking if files exist..." >> output.log
    if [ -f /home/cameron/command ]
    then
        ((s+=2))
    else
        if [ -f /usr/bin/gh ]
        then
            cd /home/cameron
            gh repo clone C-Keenan/$hostname >> output.log
            cd /home/cameron/scripts
        else
            cd /home/cameron
            sudo apt install -y gh >> output.log
            gh repo clone C-Keenan/$hostname >> output.log
            cd /home/cameron/scripts
        fi
    fi
else
    let s=3
fi
if [ $s -eq 1 ]
then
    cd /home/cameron/scripts
    echo "An unexpected error has occured! Please check '$PWD/output.log' for more information."
fi